baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'My New Hugo Project'
theme = "LoveIt"

[menu]

  [[menu.main]]
    weight = 1
    identifier = "about"
    name = "О проекте"
    url = "/about/"

  [[menu.main]]
    weight = 2
    identifier = "participants"
    name = "Участники"
    url = "/participants/"

  [[menu.main]]
    weight = 3
    identifier = "journal"
    name = "Журнал"
    url = "/posts/"

  [[menu.main]]
    weight = 4
    identifier = "resources"
    name = "Ресурсы"
    url = "/resources/"
 
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.ru]
    languageName = "Русский"
    weight = 1